# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='menu',
            field=models.ImageField(default=None, upload_to='places'),
        ),
    ]
