# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20160913_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=None, upload_to='places'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.IntegerField(choices=[(1, 'TRY'), (2, 'EUR'), (3, 'USD')], default=1),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
