# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20160913_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=None, upload_to='places'),
        ),
    ]
