# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='places')),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Media'),
        ),
        migrations.AddField(
            model_name='item',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Media'),
        ),
    ]
