# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_remove_media_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Media'),
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(default=None, upload_to='places'),
        ),
        migrations.AddField(
            model_name='place',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Media'),
        ),
    ]
