# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20160913_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(default=None, upload_to='static/images'),
        ),
    ]
